spring:
  application:
    name: userServices1
# Eureka Server Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  error:
    whitelabel:
      enabled: false

spring:
  cloud:
    compatibility-verifier:
      enabled: false

